name: Makefile CI


on:
  push:
    # branches: [ "master" ]
  pull_request:
    # branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    # runs-on: ubuntu-18.04
    runs-on: [self-hosted, linux]

    steps:
    # - uses: actions/checkout@v3
    
    - name: Build
      run: |
        cd gravity
        git checkout .
        git clean -dfx
        export JAVA_HOME=/opt/java/jdk8/
        ./configure --with-protobuf-libdir=/usr/local/lib --with-protobuf-incdir=/usr/include --with-zeromq-libdir=/usr/lib/x86_64-linux-gnu --with-zeromq-incdir=/usr/include --with-protoc=/usr/local/bin/protoc JAVAPROTOBUF_DIR=/usr/share/java/protobuf-3.6.1.jar GUAVAJAR_DIR="$PWD"/src/api/MATLAB/guava-13.0.1.jar CPPFLAGS=-std=c++11 PYTHON=python3 PYTHON_CONFIG=/usr/local/lib/python3.6/dist-packages/config.py PYTHON_INCLUDE=-I/usr/include/python3.6m
        make
        
    - name: Test
      run: make test


    # - name: configure
    #   run: ./configure
      
    # - name: Install dependencies
    #   run: make
      
    # - name: Run check
    #   run: make check
      
    # - name: Run distcheck
    #   run: make distcheck
