name: Makefile CI


on:
  push:
    # branches: [ "master" ]
  pull_request:
    # branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    # runs-on: ubuntu-18.04
    runs-on: [self-hosted, linux]

    steps:
    # - uses: actions/checkout@v3
    
    - name: Test
      run: |
        cd gravity
        git status
        cd ..


    # - name: configure
    #   run: ./configure
      
    # - name: Install dependencies
    #   run: make
      
    # - name: Run check
    #   run: make check
      
    # - name: Run distcheck
    #   run: make distcheck
